### ISSUE TITLE
ASN1 RFC5915 Decoding

### ISSUE THREAD

**Issue by rmspeers** [relocately/ec-key#1]
When decoding a P-256 key as generated to PEM by Python's cryptography library, I am getting issues decoding it.

I found that the object ID that it was using is missing from the RFC 5915 key decoding. This was resolved _for decoding_ by changing the function to have one extra line:
```
const ASN1ECRfc5915Key = asn.define('Rfc5915Key', function() {
  this.seq().obj(
    this.key('version').int(),
    this.key('privateKey').octstr(),
    this.key('parameters').optional().explicit(0).objid({
      '1 2 840 10045 3 1 7' : 'prime256v1',
      '1 3 132 0 10'        : 'prime256v1',
      '1 3 132 0 34'        : 'secp384r1',
      '1 3 132 0 35'        : 'secp521r1',
    }),
    this.key('publicKey').optional().explicit(1).bitstr()
  );
});
```

More testing is needed to ensure that your encoding, and other key decoding works. I can provide Python code to generate the key files if needed.

**Comment by pfumagalli** [comment]
OpenSSL is using the [1.2.840.10045.3.1.7 (ANSI)](http://www.oid-info.com/get/1.2.840.10045.3.1.7) OID, rather than the [1.3.132.0.10 (Certicom)](http://www.oid-info.com/get/1.3.132.0.10) one.

I'm perfectly fine in adding that OID in the decoding phase, but I'd rather the encoding part as-is and as close to OpenSSL as possible, if it works on the Python side.

If you have some sample data, feel free to add it to the `/test/support/...` files and submit a pull request.

**Comment by pfumagalli** [comment]
Fixed the decoding part, and pushed to NPM as 0.0.1.

**Comment by rmspeers** [comment]
Thank you. I'll test and add test files in a PR.

**Comment by rmspeers** [comment]
I have gone ahead and tested this, and noticed one issue. The implementation treats this new OID and curve secp256k1 as the existing curve you had, secp256r1. These are actually different curves, despite some similarities in modulus size. We should to treat these as unique curves, as their parameters differ.

I have thus created a branch and PR (https://github.com/relocately/ec-key/pull/2), added test data, etc for your consideration. Tests are passing for all existing and for the new curve.
