### ISSUE TITLE
import in Angular 10

### ISSUE THREAD

**Issue by mTLamouchi** [relocately/ec-key#10]
Hi, when using ec-key in angular I get "this.keys is undefined" is undefined :
![image](https://user-images.githubusercontent.com/75030389/114107899-cf60ad00-98c9-11eb-96b6-0b50765de09e.png)
I have setup up crypto-browserify in angular ts-config.json like this:
`  "paths": {
      "crypto": ["../node_modules/crypto-browserify"]
    }`
but that didn't work

**Comment by VenturingVenturer** [comment]
Did any one figure out how to use ec-key in Angular?

**Comment by pfumagalli** [comment]
This relies on Node's version of the `crypto` library (with all bells and whistles). The `crypto-browserify` version of it is not supported.

The issue lies in https://github.com/crypto-browserify/createECDH, look at line 92: `this.keys` is set to `void 0` in line 53 and therefore we can't _set_ the public key without it.

**Comment by VenturingVenturer** [comment]
Thank you very much for your quick response and thanks a lot for supporting the ec-key wrapper.

I profusly apologize for going beyond the scope of ec-key but are you aware of any other EC library that could be used for  signing message payloads in Angular apps?

Thanks a again for your response.

**Comment by pfumagalli** [comment]
It's baked into _every_ browser already. You don't need a library to sign...

https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign

**Comment by VenturingVenturer** [comment]
You are providing awesome support!
Thanks again.
